Catalyst_count/urls.py
from django.contrib import admin
from django.urls import path,include
from login_signup import views as login_views
from upload_data import views
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_signup/',include('login_signup.urls')),
    path('upload_data/',include('upload_data.urls')),
    path('upload_data_api/',include('upload_data.api_urls')),
    path('',login_views.signup)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload_data/urls.py
from django.urls import path
from upload_data import views

app_name = 'upload_data'

urlpatterns = [
    path('upload_data/', views.upload_data,name='upload_data'),
    path('query_builder/', views.query_builder_view,name='query_builder_view'),
    ]

upload_data/models.py
from django.db import models

# Create your models here.

class Companies(models.Model):
    company_id = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    company_domain = models.CharField(max_length=255)
    year_founded = models.CharField(max_length=255)
    industry = models.CharField(max_length=255)
    size_range = models.CharField(max_length=255)
    locality = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    linked_in_url = models.CharField(max_length=255)
    current_employee_est = models.CharField(max_length=255)
    total_employee_est = models.CharField(max_length=255)

    def __str__(self):
        return str(self.company_name)

    class Meta:
        # Define indexes for country and locality fields
        indexes = [
            models.Index(fields=['country']),
            models.Index(fields=['locality']),
        ]

upload_data/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
import csv
import traceback
from upload_data.models import Companies
from django.db import transaction
import requests
from rest_framework.test import APIClient
from django.test import TestCase
from upload_data.test import QueryBuilderAPITestCase

from django import forms

class UploadForm(forms.Form):
    upload_csv = forms.FileField(label='Upload CSV')


@transaction.atomic
def upload_data(request, template_name='upload_data/upload_data.html'):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['upload_csv']
            if not csv_file.name.endswith('.csv'):
                messages.error(request, 'Please upload a CSV file.')
                return HttpResponseRedirect(reverse('upload_data:upload_data'))

            try:
                decoded_file = csv_file.read().decode('utf-8').splitlines()
                reader = csv.reader(decoded_file)

                companies_to_create = []
                for row_number, row in enumerate(reader, start=1):
                    # Handle empty fields by setting default values
                    row += [''] * (11 - len(row))  # Fill empty fields with empty strings

                    company = Companies(
                        company_id=row[0],
                        company_name=row[1],
                        company_domain=row[2],
                        year_founded=row[3],
                        industry=row[4],
                        size_range=row[5],
                        locality=row[6],
                        country=row[7],
                        linked_in_url=row[8],
                        current_employee_est=row[9],
                        total_employee_est=row[10]
                    )
                    companies_to_create.append(company)

                # Bulk create the objects
                Companies.objects.bulk_create(companies_to_create)

                messages.success(request, 'CSV file uploaded successfully.')
                return HttpResponseRedirect(reverse('upload_data:upload_data'))
            except Exception as e:
                messages.error(request, f'Error occurred: {e}')
                print("Error occurred:", e)
                print(traceback.format_exc())  # Print the full traceback
    else:
        form = UploadForm()

    return render(request,template_name,locals())

def query_builder_view(request,template_name = 'upload_data/query_builder.html'):
    result_count = Companies.objects.all().values('id').count()
    countries = Companies.objects.all().values_list('country',flat=True).distinct()
    localities = Companies.objects.exclude(locality='').values_list('locality', flat=True).distinct()
    industries = Companies.objects.all().values_list('industry', flat=True).distinct()
    sliced_cities = []
    for locality in localities:
        if locality:
            city = locality.split(',')[0].strip()
            sliced_cities.append(city)
    sliced_cities = sliced_cities[0:30]
    print(sliced_cities)
    if request.method == 'POST':
        industry = request.POST.get('industry')
        state = request.POST.get('state')
        city = request.POST.get('city')
        country = request.POST.get('country')
        employee_from = request.POST.get('employee_from')
        employee_to = request.POST.get('employee_to')
        search_keyword = request.POST.get('search_keyword')
        api_relative_url = 'upload_data_api/api/v1/upload_data_api/'
        api_url = 'http://127.0.0.1:8000/' + api_relative_url
        payload = {
            'industry': industry,
            'state': state,
            'city': city,
            'country': country,
            'employee_from': employee_from,
            'employee_to': employee_to,
            'search_keyword': search_keyword
        }
        response = requests.get(api_url, params=payload)
        print(response.json())
        response_data = response.json()
        try:
            result_count = response_data['data']['Result Count']
        except Exception as e:
            result_count = 0

    return render(request, template_name, locals())

templates/upload_data/query_builder.html
{% extends "owner_site_base.html" %}
<!doctype html>
{% load static %}
{% block owner_site_content %}
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <style>
      </style>
      <title>Catalyst Query Builder</title>
   </head>
   <body>       <form method="post">
                    {% csrf_token %}

                    <div class="row" style="margin-top: 20px;">
                        <h2>{{ result_count }} Records Found</h2>
                    </div>

                    <div class="row" style="margin-top: 20px;">
                        <div class="form-group">
                           <div class="col-md-4 col-sm-12 col-xs-12">
                              <div class="input-group">
                                 <input type="text" id="id_search" name="keyword" placeholder="keyword" value="{{keyword}}" class="form-control col-md-7 col-xs-12" style="border-radius: 5px;">
                                 <span class="input-group-btn">
                                 <input type="submit" name="search_btn" class="btn btn-default pull-right" value="Search" style="color: #fff;background-color: #081549;border-radius: 5px;margin-left: 10px;">
                                 </span>
                              </div>
                           </div>
                           <hr/>
                           <div class="col-md-12 col-sm-12 col-xs-12  pull-right">
                              <div class="row" >
                                 <div class="x_panel" style="box-shadow: 2px 3px 28px 0px rgba(66,66,66,0.36); background-color: #081549;border-radius: 5px;">

                                 <div>

                                    <div class="col-md-2 col-sm-3 col-xs-6 mob-sm-sale-register-menu pull-left">
                                       <label class="control-label" for="id_Service" style="padding-left:10px;color: #fff;"> Country </label>
                                       <select name="country" id ="id_services"
                                            class="form-control col-md-7 col-xs-12">
                                            <option value="" >All Country</option>
                                            {% for country_option  in countries %}
                                                <option value="{{ country_option }}" {% if country_option == country %} selected {% endif %}>{{ country_option }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <div class="col-md-2 col-sm-3 col-xs-6 mob-sm-sale-register-menu pull-left">
                                        <label class="control-label" for="id_Service" style="padding-left:10px;color: #fff;">Year Founder</label>
                                        <select name="year" id="id_services" class="form-control col-md-7 col-xs-12">
                                            <option value="">All Year</option>
                                            <option value="1980" {% if year == '1980' %} selected {% endif %}>1980</option>
                                            <option value="1981" {% if year == '1981' %} selected {% endif %}>1981</option>
                                            <option value="1982" {% if year == '1982' %} selected {% endif %}>1982</option>
                                            <option value="1983" {% if year == '1983' %} selected {% endif %}>1983</option>
                                            <option value="1984" {% if year == '1984' %} selected {% endif %}>1984</option>
                                            <option value="1985" {% if year == '1985' %} selected {% endif %}>1985</option>
                                            <option value="1986" {% if year == '1986' %} selected {% endif %}>1986</option>
                                            <option value="1987" {% if year == '1987' %} selected {% endif %}>1987</option>
                                            <option value="1988" {% if year == '1988' %} selected {% endif %}>1988</option>
                                            <option value="1989" {% if year == '1989' %} selected {% endif %}>1989</option>
                                            <option value="1990" {% if year == '1990' %} selected {% endif %}>1990</option>
                                            <option value="1991" {% if year == '1991' %} selected {% endif %}>1991</option>
                                            <option value="1992" {% if year == '1992' %} selected {% endif %}>1992</option>
                                            <option value="1993" {% if year == '1993' %} selected {% endif %}>1993</option>
                                            <option value="1994" {% if year == '1994' %} selected {% endif %}>1994</option>
                                            <option value="1995" {% if year == '1995' %} selected {% endif %}>1995</option>
                                            <option value="1996" {% if year == '1996' %} selected {% endif %}>1996</option>
                                            <option value="1997" {% if year == '1997' %} selected {% endif %}>1997</option>
                                            <option value="1998" {% if year == '1998' %} selected {% endif %}>1998</option>
                                            <option value="1999" {% if year == '1999' %} selected {% endif %}>1999</option>
                                            <option value="2000" {% if year == '2000' %} selected {% endif %}>2000</option>
                                            <option value="2001" {% if year == '2001' %} selected {% endif %}>2001</option>
                                            <option value="2002" {% if year == '2002' %} selected {% endif %}>2002</option>
                                            <option value="2003" {% if year == '2003' %} selected {% endif %}>2003</option>
                                            <option value="2004" {% if year == '2004' %} selected {% endif %}>2004</option>
                                            <option value="2005" {% if year == '2005' %} selected {% endif %}>2005</option>
                                            <option value="2006" {% if year == '2006' %} selected {% endif %}>2006</option>
                                            <option value="2007" {% if year == '2007' %} selected {% endif %}>2007</option>
                                            <option value="2008" {% if year == '2008' %} selected {% endif %}>2008</option>
                                            <option value="2009" {% if year == '2009' %} selected {% endif %}>2009</option>
                                            <option value="2010" {% if year == '2010' %} selected {% endif %}>2010</option>
                                            <option value="2011" {% if year == '2011' %} selected {% endif %}>2011</option>
                                            <option value="2012" {% if year == '2012' %} selected {% endif %}>2012</option>
                                            <option value="2013" {% if year == '2013' %} selected {% endif %}>2013</option>
                                            <option value="2014" {% if year == '2014' %} selected {% endif %}>2014</option>
                                            <option value="2015" {% if year == '2015' %} selected {% endif %}>2015</option>
                                            <option value="2016" {% if year == '2016' %} selected {% endif %}>2016</option>
                                            <option value="2017" {% if year == '2017' %} selected {% endif %}>2017</option>
                                            <option value="2018" {% if year == '2018' %} selected {% endif %}>2018</option>
                                            <option value="2019" {% if year == '2019' %} selected {% endif %}>2019</option>
                                            <option value="2020" {% if year == '2020' %} selected {% endif %}>2020</option>
                                            <option value="2021" {% if year == '2021' %} selected {% endif %}>2021</option>
                                            <option value="2022" {% if year == '2022' %} selected {% endif %}>2022</option>
                                            <option value="2023" {% if year == '2023' %} selected {% endif %}>2023</option>
                                            <option value="2024" {% if year == '2024' %} selected {% endif %}>2024</option>
                                        </select>
                                    </div>

                                    <div class="col-md-2 col-sm-3 col-xs-12">
                                        <label class="control-label" for="id_membership_plan"style="color: #fff;">City</label>
                                        <select name="city"
                                           id="id_trainer" class="form-control col-md-7 col-xs-12">
                                           <option value="" >All City</option>
                                           {% for city_option in sliced_cities %}
                                                <option value="{{ city_option }}" {% if city_option == city %} selected {% endif %}>{{ city_option }}</option>
                                            {% endfor %}
                                        </select>
                                     </div>

                                 <div class="col-md-2 col-sm-3 col-xs-12">
                                        <label class="control-label" for="id_membership_plan"style="color: #fff;">Industry</label>
                                        <select name="industry"
                                           id="" class="form-control col-md-7 col-xs-12">
                                           <option value="" >All Industries</option>
                                           {% for industry in industries %}
                                                <option value="{{ industry }}" {% if industry == industry %} selected {% endif %}>{{ industry }}</option>
                                            {% endfor %}
                                        </select>
                                     </div>

                                  <div class="col-md-2 col-sm-3 col-xs-12">
                                        <label class="control-label" for="id_membership_plan"style="color: #fff;">Employee From</label>
                                         <input type="text" id="" name="employee_from" placeholder="Employee From" value="{{employee_from}}" class="form-control col-md-7 col-xs-12" style="border-radius: 5px;">

                                     </div>

                                  <div class="col-md-2 col-sm-3 col-xs-12">
                                        <label class="control-label" for="id_membership_plan"style="color: #fff;">Employee To</label>

                                         <input type="text" id="" name="employee_to" placeholder="Employee To" value="{{employee_to}}" class="form-control col-md-7 col-xs-12" style="border-radius: 5px;">

                                     </div>

                                 <br>
                                 </div>
                                 </div>
                              </div>
                           </div>

                     </div>

        </form>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   </body>
</html>
{% endblock %}

templates/upload_data/upload_data.html
{% extends "owner_site_base.html" %}
<!doctype html>
{% load static %}
{% block owner_site_content %}
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <style>
      </style>
      <title>Catalyst Upload Data</title>
   </head>
   <body>
      <div class="right_col" role="main">
         <div class="">
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="x_panel">
                     <div class="x_title">
                        <h2 style="margin-top: 20px;">Catalyst Upload Data  <small> Page</small></h2>
                     </div>
                     <div class="x_content">
                        <form action="" method="post" id="import_id" enctype="multipart/form-data" class="form-horizontal form-label-left">
                           {%csrf_token%}

                           <div class="form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12"><i class="fa fa-upload" style="font-size: 21px;"></i>
                              </label>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                                 <div  class="message_wrapper">
                                    <h4 class="heading">Upload Data</h4>
                                    <blockquote style="font-size: 13px;"  class="message">
                                       Make sure you are using a csv file.
                                    </blockquote>
                                 </div>
                              </div>
                           </div>
                           <div class="form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12">Upload CSV Data<span class="required">*</span>
                              </label>

                              <div class="col-md-6 col-sm-6 col-xs-12" style="margin-top: 10px;">
                                 <input type="file" id="id_upload_csv" name="upload_csv"
                                    oninvalid="this.setCustomValidity('Please upload the CSV file')" oninput="this.setCustomValidity('')"
                                    required="required" value="" class="form-control col-md-7 col-xs-12">
                              </div>
                           </div>
                           <div class="ln_solid"></div>
                           <div class="form-group">
                              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 " style="margin-top: 10px;">
                                 <input type="submit" name="upload_data_save" class="btn btn-success pull-right" value="Upload CSV">
                              </div>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   </body>
</html>
{% endblock %}